### ISSUE TITLE
Usertype can't be found on fresh import

### ISSUE THREAD

**Issue by Reava** [Pokeyi/VRC-Omni-Action#5]
Just imported the package, everything is up to date, no other errors other than from yours, can't seem to find where it comes from, restarting or reimporting doesnt work.

Assets/Pokeyi/UdonSharp/OmniAction/P_OmniAction.cs(13,4): System.Exception: User type P_OmniAction could not be found

**Comment by Pokeyi** [comment]
Can be solved temporarily by importing [VRC-Haptics-Profile](https://github.com/Pokeyi/VRC-Haptics-Profile) first. I will fix this to be a generic behaviour reference instead.

**Comment by Pokeyi** [comment]
Fixed in v1.0.1.
